services:
  web:
    # ポートフォワードをリセット(テスト環境で閉じておく)
    ports:
      - 80
    depends_on:
      - selenium
    volumes:
      - ./:/workspaces

  selenium:
    image: seleniarm/standalone-chromium
    ports:
      - "4444:4444" # Selenium grid server
      - "5900:5900" # VNC server
      - "7900:7900" # NoVNC server
    shm_size: 2gb
